import { Style } from '@react-pdf/types';

// This is a simplified mapping of Tailwind classes to React-PDF styles
export const tailwindToReactPDFMap: Record<string, Style> = {
  // Text colors
  'text-black': { color: '#000000' },
  'text-white': { color: '#FFFFFF' },
  'text-gray-100': { color: '#F3F4F6' },
  'text-gray-200': { color: '#E5E7EB' },
  'text-gray-300': { color: '#D1D5DB' },
  'text-gray-400': { color: '#9CA3AF' },
  'text-gray-500': { color: '#6B7280' },
  'text-gray-600': { color: '#4B5563' },
  'text-gray-700': { color: '#374151' },
  'text-gray-800': { color: '#1F2937' },
  'text-gray-900': { color: '#111827' },
  
  // Background colors
  'bg-white': { backgroundColor: '#FFFFFF' },
  'bg-black': { backgroundColor: '#000000' },
  'bg-gray-100': { backgroundColor: '#F3F4F6' },
  'bg-gray-200': { backgroundColor: '#E5E7EB' },
  'bg-gray-300': { backgroundColor: '#D1D5DB' },
  'bg-gray-400': { backgroundColor: '#9CA3AF' },
  'bg-gray-500': { backgroundColor: '#6B7280' },
  'bg-gray-600': { backgroundColor: '#4B5563' },
  'bg-gray-700': { backgroundColor: '#374151' },
  'bg-gray-800': { backgroundColor: '#1F2937' },
  'bg-gray-900': { backgroundColor: '#111827' },
  
  // Font sizes
  'text-xs': { fontSize: 12 },
  'text-sm': { fontSize: 14 },
  'text-base': { fontSize: 16 },
  'text-lg': { fontSize: 18 },
  'text-xl': { fontSize: 20 },
  'text-2xl': { fontSize: 24 },
  'text-3xl': { fontSize: 30 },
  'text-4xl': { fontSize: 36 },
  'text-5xl': { fontSize: 48 },
  
  // Font weights
  'font-thin': { fontWeight: 100 },
  'font-extralight': { fontWeight: 200 },
  'font-light': { fontWeight: 300 },
  'font-normal': { fontWeight: 400 },
  'font-medium': { fontWeight: 500 },
  'font-semibold': { fontWeight: 600 },
  'font-bold': { fontWeight: 700 },
  'font-extrabold': { fontWeight: 800 },
  'font-black': { fontWeight: 900 },
  
  // Text alignment
  'text-left': { textAlign: 'left' },
  'text-center': { textAlign: 'center' },
  'text-right': { textAlign: 'right' },
  'text-justify': { textAlign: 'justify' },
  
  // Margins
  'm-0': { margin: 0 },
  'm-1': { margin: 4 },
  'm-2': { margin: 8 },
  'm-3': { margin: 12 },
  'm-4': { margin: 16 },
  'm-5': { margin: 20 },
  'm-6': { margin: 24 },
  'm-8': { margin: 32 },
  'm-10': { margin: 40 },
  'm-12': { margin: 48 },
  
  'mt-0': { marginTop: 0 },
  'mt-1': { marginTop: 4 },
  'mt-2': { marginTop: 8 },
  'mt-3': { marginTop: 12 },
  'mt-4': { marginTop: 16 },
  'mt-5': { marginTop: 20 },
  'mt-6': { marginTop: 24 },
  'mt-8': { marginTop: 32 },
  'mt-10': { marginTop: 40 },
  'mt-12': { marginTop: 48 },
  
  'mr-0': { marginRight: 0 },
  'mr-1': { marginRight: 4 },
  'mr-2': { marginRight: 8 },
  'mr-3': { marginRight: 12 },
  'mr-4': { marginRight: 16 },
  'mr-5': { marginRight: 20 },
  'mr-6': { marginRight: 24 },
  'mr-8': { marginRight: 32 },
  'mr-10': { marginRight: 40 },
  'mr-12': { marginRight: 48 },
  
  'mb-0': { marginBottom: 0 },
  'mb-1': { marginBottom: 4 },
  'mb-2': { marginBottom: 8 },
  'mb-3': { marginBottom: 12 },
  'mb-4': { marginBottom: 16 },
  'mb-5': { marginBottom: 20 },
  'mb-6': { marginBottom: 24 },
  'mb-8': { marginBottom: 32 },
  'mb-10': { marginBottom: 40 },
  'mb-12': { marginBottom: 48 },
  
  'ml-0': { marginLeft: 0 },
  'ml-1': { marginLeft: 4 },
  'ml-2': { marginLeft: 8 },
  'ml-3': { marginLeft: 12 },
  'ml-4': { marginLeft: 16 },
  'ml-5': { marginLeft: 20 },
  'ml-6': { marginLeft: 24 },
  'ml-8': { marginLeft: 32 },
  'ml-10': { marginLeft: 40 },
  'ml-12': { marginLeft: 48 },
  
  // Paddings
  'p-0': { padding: 0 },
  'p-1': { padding: 4 },
  'p-2': { padding: 8 },
  'p-3': { padding: 12 },
  'p-4': { padding: 16 },
  'p-5': { padding: 20 },
  'p-6': { padding: 24 },
  'p-8': { padding: 32 },
  'p-10': { padding: 40 },
  'p-12': { padding: 48 },
  
  'pt-0': { paddingTop: 0 },
  'pt-1': { paddingTop: 4 },
  'pt-2': { paddingTop: 8 },
  'pt-3': { paddingTop: 12 },
  'pt-4': { paddingTop: 16 },
  'pt-5': { paddingTop: 20 },
  'pt-6': { paddingTop: 24 },
  'pt-8': { paddingTop: 32 },
  'pt-10': { paddingTop: 40 },
  'pt-12': { paddingTop: 48 },
  
  'pr-0': { paddingRight: 0 },
  'pr-1': { paddingRight: 4 },
  'pr-2': { paddingRight: 8 },
  'pr-3': { paddingRight: 12 },
  'pr-4': { paddingRight: 16 },
  'pr-5': { paddingRight: 20 },
  'pr-6': { paddingRight: 24 },
  'pr-8': { paddingRight: 32 },
  'pr-10': { paddingRight: 40 },
  'pr-12': { paddingRight: 48 },
  
  'pb-0': { paddingBottom: 0 },
  'pb-1': { paddingBottom: 4 },
  'pb-2': { paddingBottom: 8 },
  'pb-3': { paddingBottom: 12 },
  'pb-4': { paddingBottom: 16 },
  'pb-5': { paddingBottom: 20 },
  'pb-6': { paddingBottom: 24 },
  'pb-8': { paddingBottom: 32 },
  'pb-10': { paddingBottom: 40 },
  'pb-12': { paddingBottom: 48 },
  
  'pl-0': { paddingLeft: 0 },
  'pl-1': { paddingLeft: 4 },
  'pl-2': { paddingLeft: 8 },
  'pl-3': { paddingLeft: 12 },
  'pl-4': { paddingLeft: 16 },
  'pl-5': { paddingLeft: 20 },
  'pl-6': { paddingLeft: 24 },
  'pl-8': { paddingLeft: 32 },
  'pl-10': { paddingLeft: 40 },
  'pl-12': { paddingLeft: 48 },
  
  // Flex
  'flex': { display: 'flex' },
  'flex-row': { flexDirection: 'row' },
  'flex-col': { flexDirection: 'column' },
  'flex-wrap': { flexWrap: 'wrap' },
  'flex-nowrap': { flexWrap: 'nowrap' },
  'flex-1': { flex: 1 },
  'flex-auto': { flex: 'auto' },
  'flex-initial': { flex: 'initial' },
  'flex-none': { flex: 'none' },
  
  // Justify content
  'justify-start': { justifyContent: 'flex-start' },
  'justify-end': { justifyContent: 'flex-end' },
  'justify-center': { justifyContent: 'center' },
  'justify-between': { justifyContent: 'space-between' },
  'justify-around': { justifyContent: 'space-around' },
  'justify-evenly': { justifyContent: 'space-evenly' },
  
  // Align items
  'items-start': { alignItems: 'flex-start' },
  'items-end': { alignItems: 'flex-end' },
  'items-center': { alignItems: 'center' },
  'items-baseline': { alignItems: 'baseline' },
  'items-stretch': { alignItems: 'stretch' },
  
  // Border
  'border': { borderWidth: 1, borderStyle: 'solid', borderColor: '#E5E7EB' },
  'border-0': { borderWidth: 0 },
  'border-2': { borderWidth: 2 },
  'border-4': { borderWidth: 4 },
  'border-8': { borderWidth: 8 },
  
  'border-t': { borderTopWidth: 1, borderStyle: 'solid', borderColor: '#E5E7EB' },
  'border-r': { borderRightWidth: 1, borderStyle: 'solid', borderColor: '#E5E7EB' },
  'border-b': { borderBottomWidth: 1, borderStyle: 'solid', borderColor: '#E5E7EB' },
  'border-l': { borderLeftWidth: 1, borderStyle: 'solid', borderColor: '#E5E7EB' },
  
  // Border radius
  'rounded-none': { borderRadius: 0 },
  'rounded-sm': { borderRadius: 2 },
  'rounded': { borderRadius: 4 },
  'rounded-md': { borderRadius: 6 },
  'rounded-lg': { borderRadius: 8 },
  'rounded-xl': { borderRadius: 12 },
  'rounded-2xl': { borderRadius: 16 },
  'rounded-3xl': { borderRadius: 24 },
  'rounded-full': { borderRadius: 9999 },
  
  // Width and height
  'w-full': { width: '100%' },
  'w-auto': { width: 'auto' },
  'h-full': { height: '100%' },
  'h-auto': { height: 'auto' },
  
  // Shadcn-like styles
  'shadcn-button': {
    backgroundColor: '#111827',
    color: '#FFFFFF',
    padding: 8,
    borderRadius: 4,
    fontWeight: 500,
  },
  'shadcn-card': {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#E5E7EB',
  },
  'shadcn-input': {
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#D1D5DB',
    borderRadius: 4,
    padding: 8,
  },
};